let a = 10;
let b = 20;
console.log("Initialized Values a=",a,"b=",b);
console.log("Arithimatic operations:");
console.log("a+b: ",a+b,"a-b:", a-b,"a*b:", a*b,"a/b:", a/b,"a%b:", a%b);
console.log("-------------------------------------------------------------------------------");
console.log("Relational operations: ");
console.log("a>b, a<b, a<=b, a>=b  :",a>b, a<b, a<=b, a>=b);
console.log("-------------------------------------------------------------------------------");
console.log("Increment/decrement Operations: ");
console.log("a++,b++,a--,b--  :",a++,b++,a--,b--);
console.log("-------------------------------------------------------------------------------");
console.log("Bitwise Operations: ");
console.log("a & b, a|b, a^b, ~a, ~b, a<<b, a>>b, a>>>b   :",a & b, a|b, a^b, ~a, ~b, a<<b, a>>b, a>>>b);
console.log("-------------------------------------------------------------------------------");
console.log("Assignment Operations: ");
let c=a;
let d=b;
console.log("c= ",c,"d= ",d);
console.log("-------------------------------------------------------------------------------");
console.log("Conditional Operations: ")
console.log("a>b?a is greater':b is greater   :",a>b?"a is greater":"b is greater");
console.log("-------------------------------------------------------------------------------");
console.log("Special Operatons: ");
console.log("Type of a is :",typeof(a));
console.log("-------------------------------------------------------------------------------");
console.log("Logical Operations: ");
console.log("a && b, a || b, !a   :",a && b, a || b, !a);